#!/usr/bin/env node
import http from 'node:http';
import { readFile } from 'node:fs/promises';
import { spawn } from 'node:child_process';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildPlannerArtifacts, buildPlannerArtifactsFromData } from '../planner/io.js';
import { daysUntilTarget, acquisitionPhase } from '../planner/kit-plan.js';
import { priceDropSummary } from '../planner/history.js';
import { blobStorageConfigured, loadWeeklyState } from '../cron/blob-storage.js';
import { BlobStorage } from '../cron/blob-storage.js';
import { executeWeeklyCrawl, isAuthorizedCron } from '../cron/weekly.js';
import { importBaseline } from '../cron/import-baseline.js';
import { loadDefaultProfile, normalizeProfile, publicProfile } from '../profiles.js';
import { gunzipSync } from 'node:zlib';

const projectRoot=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..'),publicDir=path.join(projectRoot,'src/dashboard/public'),port=Number(process.env.PORT??4173),host=process.env.VERCEL?'0.0.0.0':'127.0.0.1',isHosted=Boolean(process.env.VERCEL),dashboardDryRun=process.env.PG_DASHBOARD_DRY_RUN!=='false',jobs=new Map();
const commandMap={
  'crawl-fixtures':{label:'Fixture dry run',command:process.execPath,args:['src/cli.js','--source','paragliding-secondhand','--dry-run','--fixture-only','--max-listings','5','--batch-size','2']},
  'crawl-live-five':{label:'Live 5-listing dry run',command:process.execPath,args:['src/cli.js','--source','paragliding-secondhand','--dry-run','--max-listings','5','--batch-size','2']},
  'market-stats':{label:'Update market statistics',command:process.execPath,args:['src/commands/update-market-stats.js','--dry-run']},
  'watchlist':{label:'Evaluate watchlist',command:process.execPath,args:['src/commands/evaluate-watchlist.js','--dry-run']},
  'plan':{label:'Build acquisition plan',command:process.execPath,args:['src/commands/build-acquisition-plan.js','--dry-run','--kit-plan','griffin-primary-kit']},
  'report':{label:'Generate acquisition report',command:process.execPath,args:['src/commands/acquisition-report.js','--dry-run','--kit-plan','griffin-primary-kit']},
  'tests':{label:'Run test suite',command:process.execPath,args:['--test']}
};
const send=(res,status,value,type='application/json; charset=utf-8')=>{res.writeHead(status,{'content-type':type,'cache-control':'no-store'});res.end(type.startsWith('application/json')?JSON.stringify(value):value);};
async function profilesData(state=null){const fallback=await loadDefaultProfile(),saved=state?.profiles??{};return Object.values({[fallback.id]:fallback,...saved}).map(publicProfile);}
const watchlistForProfile=profile=>profile.watchlist.map(rule=>({...rule,requirePorosityPass:rule.requirePorosityPass??(rule.equipmentType==='wing'&&profile.plan.requireWingPorosityPass),requireInspectionReport:rule.requireInspectionReport??profile.plan.requireInspectionReport}));
async function dashboardData(profileId){let weeklyState=null,a,profiles;if(isHosted&&blobStorageConfigured()){weeklyState=await loadWeeklyState();profiles=await profilesData(weeklyState);const selected=profiles.find(x=>x.id===profileId)??profiles[0];a=await buildPlannerArtifactsFromData({listings:weeklyState.listings,savedHistory:weeklyState.history,basePlan:selected.plan,watchlist:watchlistForProfile(selected),options:{dryRun:true,kitPlanId:selected.id}});}else{profiles=await profilesData();const selected=profiles.find(x=>x.id===profileId)??profiles[0],local=await buildPlannerArtifacts({dryRun:dashboardDryRun,kitPlanId:'griffin-primary-kit'});a=selected.id==='griffin-primary-kit'?local:await buildPlannerArtifactsFromData({listings:local.listings,savedHistory:local.history,basePlan:selected.plan,watchlist:watchlistForProfile(selected),options:{dryRun:dashboardDryRun,kitPlanId:selected.id}});}const drops=a.history.map(x=>priceDropSummary(x)).filter(x=>x?.absoluteDrop>0).sort((x,y)=>y.percentDrop-x.percentDrop).slice(0,8),recent=a.history.filter(x=>x.lifecycleEvents.some(e=>e.type==='new-listing')).slice(-8).reverse().map(x=>({listingId:x.listingId,title:x.observations.at(-1)?.title,sourceUrl:x.sourceUrl,firstSeenAt:x.firstSeenAt}));return{localOnly:!isHosted,hosted:isHosted,storageConfigured:blobStorageConfigured(),weeklyRun:weeklyState?.lastRun??null,profiles,activeProfileId:a.plan.kitPlanId,plan:a.plan,daysRemaining:daysUntilTarget(a.plan),phase:acquisitionPhase(a.plan),report:a.report,scenarios:a.scenarios,watchMatches:a.watchMatches,alerts:a.alerts,marketStats:a.stats.groups,priceDrops:drops,newListings:recent,historyCount:a.history.length,commands:isHosted?[]:Object.entries(commandMap).map(([id,x])=>({id,label:x.label})),jobs:isHosted?[]:[...jobs.values()].slice(-8).reverse()};}
function listingFit(listing,profile){const issues=[],manual=[],plan=profile.plan,text=listing.description??'';if(listing.listingType==='wing'){const range=listing.equipment?.certifiedWeightRangeKg,target=plan.estimatedAllUpWeightRangeKg;if(!range)manual.push('weight range unknown');else if(target.min<range.min||target.max>range.max)issues.push('outside pilot weight range');if(plan.requireWingPorosityPass&&!/porosity[^.\n]{0,60}\b(?:pass|good|excellent)\b/i.test(text))manual.push('porosity pass not documented');}if(plan.requireInspectionReport&&!/\b(?:inspect(?:ed|ion)|trim(?:med| check)|service report)\b/i.test(text))manual.push('inspection report not documented');const allocation=plan.allocations[listing.listingType];if(allocation&&listing.price?.amount>allocation.absoluteMaximum)issues.push('above profile maximum');return{status:issues.length?'reject':manual.length?'manual-review':'candidate',issues,manualReview:manual};}
async function listingsData(params){let listings,profiles;if(isHosted&&blobStorageConfigured()){const state=await loadWeeklyState();listings=state.listings;profiles=await profilesData(state);}else{const local=await buildPlannerArtifacts({dryRun:dashboardDryRun,kitPlanId:'griffin-primary-kit'});listings=local.listings;profiles=await profilesData();}const profile=profiles.find(x=>x.id===params.get('profile'))??profiles[0],type=params.get('type'),query=(params.get('q')??'').toLowerCase(),includeUnknown=params.get('includeUnknown')==='true',maxPrice=Number(params.get('maxPrice')),limit=Math.min(500,Math.max(1,Number(params.get('limit')??200)||200));let rows=listings.filter(x=>x.location?.isNorthAmerica===true||(includeUnknown&&x.location?.isNorthAmerica==null));if(type&&type!=='all')rows=rows.filter(x=>x.listingType===type);if(query)rows=rows.filter(x=>`${x.title} ${x.manufacturer} ${x.model}`.toLowerCase().includes(query));if(Number.isFinite(maxPrice)&&maxPrice>0)rows=rows.filter(x=>x.price?.amount!=null&&x.price.amount<=maxPrice);rows.sort((a,b)=>(b.listedAt??b.firstSeenAt??'').localeCompare(a.listedAt??a.firstSeenAt??''));return{profileId:profile.id,total:rows.length,includeUnknown,listings:rows.slice(0,limit).map(x=>({id:x.id,title:x.title,sourceUrl:x.sourceUrl,listingType:x.listingType,price:x.price,location:x.location,listedAt:x.listedAt,listingAgeDays:x.listingAgeDays,manufacturer:x.manufacturer,model:x.model,equipment:x.equipment,bundle:x.bundle,fit:listingFit(x,profile),retailComparison:null}))};}
async function readJsonBody(req,{maxBytes=1_000_000,maxDecodedBytes=2_000_000}={}){const chunks=[];let size=0;for await(const chunk of req){size+=chunk.length;if(size>maxBytes)throw new Error('Request body is too large');chunks.push(chunk);}let body=Buffer.concat(chunks);if(req.headers['content-encoding']==='gzip')body=gunzipSync(body);if(body.length>maxDecodedBytes)throw new Error('Decoded request body is too large');return JSON.parse(body.toString('utf8')||'{}');}
async function saveProfile(req,id){if(!blobStorageConfigured())return{status:503,value:{error:'Connect a private Vercel Blob store before saving profiles.'}};if(!isAuthorizedCron(req.headers))return{status:401,value:{error:'Unauthorized'}};const profile=normalizeProfile(await readJsonBody(req),id),storage=new BlobStorage();await storage.init();storage.state.profiles[id]=profile;await storage.flush();return{status:200,value:publicProfile(profile)};}
function startJob(id){const spec=commandMap[id];if(!spec)return null;const job={id:`${Date.now()}-${Math.random().toString(16).slice(2)}`,commandId:id,label:spec.label,status:'running',startedAt:new Date().toISOString(),finishedAt:null,exitCode:null,output:''};jobs.set(job.id,job);const child=spawn(spec.command,spec.args,{cwd:projectRoot,env:{...process.env,NO_COLOR:'1'}});const append=chunk=>{job.output=(job.output+chunk.toString()).slice(-100000);};child.stdout.on('data',append);child.stderr.on('data',append);child.on('error',error=>{append(error.message);job.status='failed';job.finishedAt=new Date().toISOString();});child.on('close',code=>{job.exitCode=code;job.status=code===0?'completed':'failed';job.finishedAt=new Date().toISOString();});return job;}
const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url,`http://${req.headers.host}`);if(req.method==='GET'&&url.pathname==='/api/cron/weekly'){if(!isAuthorizedCron(req.headers))return send(res,401,{error:'Unauthorized'});return send(res,200,{ok:true,run:await executeWeeklyCrawl()});}if(req.method==='POST'&&url.pathname==='/api/admin/baseline'){if(!isAuthorizedCron(req.headers))return send(res,401,{error:'Unauthorized'});return send(res,200,{ok:true,import:await importBaseline(await readJsonBody(req,{maxBytes:4_000_000,maxDecodedBytes:20_000_000}))});}if(req.method==='GET'&&url.pathname==='/api/profiles')return send(res,200,{profiles:await profilesData(isHosted&&blobStorageConfigured()?await loadWeeklyState():null),storageConfigured:blobStorageConfigured()});if(req.method==='PUT'&&url.pathname.startsWith('/api/profiles/')){const result=await saveProfile(req,decodeURIComponent(url.pathname.split('/').pop()));return send(res,result.status,result.value);}if(req.method==='GET'&&url.pathname==='/api/dashboard')return send(res,200,await dashboardData(url.searchParams.get('profile')));if(req.method==='GET'&&url.pathname==='/api/listings')return send(res,200,await listingsData(url.searchParams));if(isHosted&&url.pathname.startsWith('/api/commands/'))return send(res,403,{error:'Command execution is local-only. Hosted automation requires an authenticated job queue.'});if(req.method==='GET'&&url.pathname.startsWith('/api/jobs/')){const job=jobs.get(url.pathname.split('/').pop());return job?send(res,200,job):send(res,404,{error:'Job not found'});}if(req.method==='POST'&&url.pathname.startsWith('/api/commands/')){const job=startJob(url.pathname.split('/').pop());return job?send(res,202,job):send(res,404,{error:'Command is not allowlisted'});}if(req.method!=='GET')return send(res,405,{error:'Method not allowed'});const file=url.pathname==='/'?'index.html':url.pathname.slice(1);if(!['index.html','app.js','styles.css','profiles.css','listings.css'].includes(file))return send(res,404,'Not found','text/plain');const types={html:'text/html; charset=utf-8',js:'text/javascript; charset=utf-8',css:'text/css; charset=utf-8'};return send(res,200,await readFile(path.join(publicDir,file),'utf8'),types[file.split('.').pop()]);}catch(error){send(res,500,{error:error.message});}});
server.listen(port,host,()=>console.log(`Acquisition planner dashboard: http://${host}:${port}`));
