import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { createKitPlan } from './kit-plan.js';
import { updateListingHistory } from './history.js';
import { calculateMarketStats } from './market-stats.js';
import { evaluateWatchlist } from './watchlist.js';
import { scoreDeal, alertForListing } from './deals.js';
import { buildAcquisitionScenarios } from './scenarios.js';
import { acquisitionPhase } from './kit-plan.js';
import { buildPlannerReport } from './report.js';

async function json(pathname,fallback){try{return JSON.parse(await readFile(pathname,'utf8'));}catch{return structuredClone(fallback);}}
export function plannerPaths({dataDir='data',dryRun=true,kitPlanId='griffin-primary-kit'}={}){const root=dryRun?path.join(dataDir,'dry-run'):dataDir;return{root,listings:path.join(root,'normalized',dryRun?'normalized-preview.json':'listings.json'),history:path.join(root,'planner','listing-history.json'),stats:path.join(root,'planner','market-stats.json'),matches:path.join(root,'planner','watch-matches.json'),alerts:path.join(root,'planner','alerts-preview.json'),scenarios:path.join(root,'planner','acquisition-plan-preview.json'),report:path.join(root,'planner','acquisition-report-preview.json'),planConfig:path.join('config','kit-plans',`${kitPlanId}.json`),watchConfig:path.join('config','watchlist.json')};}
export async function buildPlannerArtifactsFromData({listings=[],savedHistory=[],options={},basePlan:providedPlan=null,watchlist:providedWatchlist=null}={}){const p=plannerPaths(options),basePlan=providedPlan??await json(p.planConfig,createKitPlan()),watchlist=providedWatchlist??await json(p.watchConfig,[]),plan={...createKitPlan(),...structuredClone(basePlan)};if(options.targetDate)plan.targetCompletionDate=options.targetDate;if(options.maxBudget!=null){plan.maximumTotalBudget.amount=options.maxBudget;plan.remainingBudget=options.maxBudget-plan.committedSpend-plan.allocations.shippingAndInspectionReserve.target;}const seeded=savedHistory.length?{histories:savedHistory,report:{newListings:[],unchangedListings:[],priceDrops:[],priceIncreases:[],relisted:[],removed:[],changed:[]}}:updateListingHistory([],listings,{observedAt:options.now??new Date().toISOString()});const stats=calculateMarketStats(seeded.histories,listings,options.now),watchMatches=evaluateWatchlist(listings,watchlist),phase=acquisitionPhase(plan,options.now),alerts=watchMatches.map(match=>{const listing=listings.find(x=>x.id===match.listingId),deal=scoreDeal(listing,stats),alert=alertForListing(listing,{watchMatch:match,deal,plan,phase});return{...alert,listingId:listing.id,title:listing.title,sourceUrl:listing.sourceUrl,deal,watchId:match.watchId};}),scenarios=buildAcquisitionScenarios(listings,plan),report=buildPlannerReport({plan,historyReport:seeded.report,marketStats:stats,watchMatches,alerts,scenarios,listings},options.now);return{paths:p,listings,history:seeded.histories,historyReport:seeded.report,stats,watchlist,watchMatches,plan,alerts,scenarios,report};}
export async function buildPlannerArtifacts(options={}){const p=plannerPaths(options),listings=await json(p.listings,[]),savedHistory=await json(p.history,[]);return buildPlannerArtifactsFromData({listings,savedHistory,options});}
export async function savePlannerArtifacts(artifacts,{includeHistory=false}={}){await mkdir(path.join(artifacts.paths.root,'planner'),{recursive:true});const writes=[[artifacts.paths.stats,artifacts.stats],[artifacts.paths.matches,artifacts.watchMatches],[artifacts.paths.alerts,artifacts.alerts],[artifacts.paths.scenarios,artifacts.scenarios],[artifacts.paths.report,artifacts.report]];if(includeHistory)writes.push([artifacts.paths.history,artifacts.history]);for(const [pathname,value]of writes)await writeFile(pathname,JSON.stringify(value,null,2));}
