const round=value=>value==null?null:Number(value.toFixed(2));
const quantile=(sorted,q)=>{if(!sorted.length)return null;const pos=(sorted.length-1)*q,lo=Math.floor(pos),hi=Math.ceil(pos);return sorted[lo]+(sorted[hi]-sorted[lo])*(pos-lo);};
function summarize(values,days,statuses){const sorted=[...values].sort((a,b)=>a-b);const q1=quantile(sorted,.25),q3=quantile(sorted,.75),iqr=q3-q1;const usable=sorted.length>=4?sorted.filter(x=>x>=q1-1.5*iqr&&x<=q3+1.5*iqr):sorted;const trim=Math.floor(usable.length*.1),trimmed=usable.slice(trim,Math.max(trim,usable.length-trim));const mean=a=>a.length?a.reduce((x,y)=>x+y,0)/a.length:null;const daySorted=[...days].sort((a,b)=>a-b);
  return{sampleSize:usable.length,rawSampleSize:sorted.length,outliersExcluded:sorted.length-usable.length,activeListingCount:statuses.filter(x=>x==='active').length,soldOrRemovedCount:statuses.filter(x=>x!=='active').length,priceLow:usable[0]??null,priceHigh:usable.at(-1)??null,medianPrice:round(quantile(usable,.5)),meanPrice:round(mean(usable)),percentile25:round(quantile(usable,.25)),percentile75:round(quantile(usable,.75)),trimmedMean:round(mean(trimmed)),observedMinimum:sorted[0]??null,observedMaximum:sorted.at(-1)??null,averageDaysListed:round(mean(days)),medianDaysListed:round(quantile(daySorted,.5)),strength:usable.length>=10?'strong':usable.length>=5?'moderate':'weak',warning:usable.length>=5?null:'Insufficient comparison data; do not treat this range as authoritative.'};}

export function calculateMarketStats(histories,listings,asOf=new Date().toISOString()) {
  const listingById=new Map(listings.map(x=>[x.id,x])),groups=new Map();
  const add=(key,dimensions,price,days,status)=>{if(!groups.has(key))groups.set(key,{key,dimensions,prices:[],days:[],statuses:[]});const g=groups.get(key);g.prices.push(price);g.days.push(days);g.statuses.push(status);};
  for(const history of histories){const listing=listingById.get(history.listingId);const observation=history.observations.at(-1);if(!listing||observation?.price?.amount==null||!observation.price.currency||listing.location?.isNorthAmerica!==true||listing.listingType==='full-kit')continue;const text=`${listing.title} ${listing.description}`;if(/\b(?:damaged|parts only|for parts|scam)\b/i.test(text))continue;const days=Math.max(0,Math.floor((Date.parse(history.lastSeenAt??asOf)-Date.parse(history.firstSeenAt))/86400000));const dims={equipmentType:listing.listingType,manufacturer:listing.manufacturer??null,model:listing.model??null,size:listing.equipment?.size??null,year:listing.equipment?.year??null,certification:listing.equipment?.certification??null,condition:listing.equipment?.condition??null,inspectionStatus:observation.inspectionDocumented?'documented':'unknown',porosityStatus:observation.porosityDocumented?'documented':'unknown',region:listing.location?.region??listing.location?.country??null,bundle:false,currency:observation.price.currency};
    add(`${dims.equipmentType}|${dims.currency}`,{equipmentType:dims.equipmentType,currency:dims.currency},observation.price.amount,days,history.status);
    if(dims.manufacturer)add(`${dims.equipmentType}|${dims.manufacturer}|${dims.currency}`,{equipmentType:dims.equipmentType,manufacturer:dims.manufacturer,currency:dims.currency},observation.price.amount,days,history.status);
    if(dims.model)add(`${dims.equipmentType}|${dims.manufacturer}|${dims.model}|${dims.currency}`,dims,observation.price.amount,days,history.status);
  }
  return{generatedAt:asOf,priceBasis:'asking-price',limitations:['Removed listings retain an unknown final price and are not assumed sold at asking price.','Weak samples are descriptive only.'],groups:[...groups.values()].map(g=>({...g.dimensions,key:g.key,...summarize(g.prices,g.days,g.statuses)}))};
}
